# Generated by Django 6.1 on 2026-08-13 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Sequence index of lesson inside skill.')),
                ('xp_reward', models.PositiveIntegerField(default=10, help_text='XP awarded upon full lesson completion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.skill')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
                'unique_together': {('skill', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRANSLATE', 'Translate / Word Bank'), ('MATCH_PAIRS', 'Match Pairs'), ('FILL_IN_BLANK', 'Fill in the Blank'), ('TYPE_ANSWER', 'Type Answer')], max_length=30)),
                ('prompt', models.TextField(help_text="Question prompt (e.g., 'Translate this sentence' or 'Select the correct image').")),
                ('audio_url', models.URLField(blank=True, help_text='Optional audio clip for pronunciation/listening exercises.', max_length=500, null=True)),
                ('content_json', models.JSONField(help_text='Dynamic payload storing choices, word bank items, options, or matching pairs.')),
                ('correct_answer', models.JSONField(help_text='Expected correct answer payload (string, array of strings, or key-value object).')),
                ('order', models.PositiveIntegerField(help_text='Sequence index inside the lesson player queue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
