# Generated by Django 5.2.1 on 2026-08-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_character_uniticon_alter_skill_unique_together_and_more'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Optional audio used by listening/pronunciation exercises.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='content_json',
            field=models.JSONField(help_text='Exercise-specific data such as options, word bank items, or matching pairs.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.JSONField(help_text='Canonical correct answer used by the backend when validating submissions.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(help_text='Sequence of the exercise within the lesson.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prompt',
            field=models.TextField(help_text='Question or instruction shown to the learner.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Sequence of the lesson within the unit.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10, help_text='XP awarded when the lesson is completed.'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_exercise_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='unique_lesson_order_per_unit'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='skill',
        ),
    ]
