"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import dj_database_url

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'users',
    'courses',
    'lessons',
    'progress',
    'gamification',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.ExceptionHandlingMiddleware',
]



ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization, Auto Field & CORS/CSRF Settings
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CORS_ALLOW_ALL_ORIGINS = True  # Allow requests from any origin
CORS_ALLOWED_ORIGINS = []  # Not needed if CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  # Required for cookies/authentication
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "https://*.onrender.com",
]
CSRF_COOKIE_SECURE = False  # Allow insecure CSRF cookies (for testing)
CSRF_COOKIE_SAMESITE = "None"  # Required for cross-origin cookies
CORS_ALLOW_HEADERS = ["*"]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

JAZZMIN_SETTINGS = {
    # Title and branding
    "site_title": "Duolingo Admin",
    "site_header": "Admin Panel",
    "site_brand": "Duolingo Clone Admin",
    "welcome_sign": "Welcome to the Duolingo Admin Panel",
    "copyright": "Duolingo Clone © 2026",

    # Sidebar settings
    "show_sidebar": True,
    "navigation_expanded": True,

    # Top menu configuration
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
    ],

    # Detailed icon mapping with FontAwesome icons
    "icons": {
        # Auth app
        "auth": "fas fa-shield-alt",
        "auth.group": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",

        # Users app
        "users": "fas fa-users",
        "users.user": "fas fa-user-graduate",
        "users.session": "fas fa-key",
        "users.dailyactivity": "fas fa-calendar-check",
        "users.usercourse": "fas fa-book-reader",

        # Courses app
        "courses": "fas fa-language",
        "courses.course": "fas fa-globe",
        "courses.section": "fas fa-layer-group",
        "courses.unit": "fas fa-cubes",
        "courses.character": "fas fa-smile",
        "courses.uniticon": "fas fa-icons",

        # Lessons app
        "lessons": "fas fa-book-open",
        "lessons.lesson": "fas fa-graduation-cap",
        "lessons.exercise": "fas fa-pen-nib",

        # Progress app
        "progress": "fas fa-chart-line",
        "progress.userunitprogress": "fas fa-tasks",
        "progress.userlessonhistory": "fas fa-history",

        # Gamification app
        "gamification": "fas fa-trophy",
        "gamification.achievement": "fas fa-award",
        "gamification.userachievement": "fas fa-medal",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Order of apps
    "order_with_respect_to": [
        "users",
        "courses",
        "lessons",
        "progress",
        "gamification",
        "auth",
    ],

    # UI Tweaks
    "changeform_format": "horizontal_tabs",
}

