# Generated by Django 6.1 on 2026-08-13 17:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_earned', models.PositiveIntegerField(default=10)),
                ('hearts_lost', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_histories', to='users.user')),
            ],
            options={
                'db_table': 'user_lesson_history',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('completed_lessons', models.PositiveIntegerField(default=0, help_text='Number of lessons completed in this skill.')),
                ('is_unlocked', models.BooleanField(default=False, help_text='Whether this skill node is accessible to the learner.')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all lessons in this skill are completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('user_id', 'skill_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='courses.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progresses', to='users.user')),
            ],
            options={
                'db_table': 'user_skill_progress',
            },
        ),
    ]
