# Generated by Django 5.2.1 on 2026-08-13 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_character_uniticon_alter_skill_unique_together_and_more'),
        ('progress', '0001_initial'),
        ('users', '0003_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonhistory',
            name='correct_answers',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of exercises answered correctly.'),
        ),
        migrations.AddField(
            model_name='userlessonhistory',
            name='total_questions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total number of exercises in the lesson.'),
        ),
        migrations.AlterField(
            model_name='userlessonhistory',
            name='completed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userlessonhistory',
            name='hearts_lost',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of hearts lost during this lesson.'),
        ),
        migrations.AlterField(
            model_name='userlessonhistory',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, help_text='XP earned from this lesson completion.'),
        ),
        migrations.CreateModel(
            name='UserUnitProgress',
            fields=[
                ('is_unlocked', models.BooleanField(default=False, help_text='Whether the user can currently access this unit.')),
                ('completed_lessons', models.PositiveIntegerField(default=0, help_text='Number of lessons completed in this unit.')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all lessons in this unit are completed.')),
                ('crown_level', models.PositiveSmallIntegerField(default=0, help_text='Current proficiency/crown level for this unit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('user_id', 'unit_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='courses.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progresses', to='users.user')),
            ],
            options={
                'db_table': 'user_unit_progress',
            },
        ),
        migrations.DeleteModel(
            name='UserSkillProgress',
        ),
    ]
