# Generated by Django 6.1 on 2026-08-15 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_skill_remove_unit_color_hex_and_more'),
        ('progress', '0002_userlessonhistory_correct_answers_and_more'),
        ('users', '0005_remove_dailyactivity_pk_dailyactivity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunitprogress',
            name='pk',
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='userunitprogress',
            constraint=models.UniqueConstraint(fields=('user', 'unit'), name='unique_user_unit_progress'),
        ),
    ]
