# Generated by Django 5.2.1 on 2026-08-13 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='UnitIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'unit_icons',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('REVIEW', 'Review'), ('LEGENDARY', 'Legendary'), ('STORY', 'Story'), ('REWARD', 'Reward'), ('MILESTONE', 'Milestone'), ('CHECKPOINT', 'Checkpoint')], default='LESSON', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='source_language',
            field=models.CharField(help_text='Language spoken by the learner, e.g. English.', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_language',
            field=models.CharField(help_text='Language being learned, e.g. Spanish.', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(help_text='Position of this unit within the section.'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='courses.character'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('target_language', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(help_text='Position of this section within the course.')),
                ('color_hex', models.CharField(default='#58CC02', help_text='Hex color used for section UI styling.', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='courses.character')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='section',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='courses.uniticon'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_unit_order_per_section'),
        ),
    ]
