# Generated by Django 5.2.1 on 2026-08-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_character_uniticon_alter_skill_unique_together_and_more'),
        ('lessons', '0002_alter_exercise_unique_together_and_more'),
        ('progress', '0002_userlessonhistory_correct_answers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_section_order_per_course'),
        ),
    ]
