# Generated by Django 6.1 on 2026-08-13 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique identifier key (e.g., STREAK_7, TOTAL_XP_1000).', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('target_value', models.PositiveIntegerField(help_text='Target threshold needed to unlock (e.g., 7 for a 7-day streak).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('user_id', 'achievement_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.user')),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
