# Generated by Django 6.1 on 2026-08-15 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('users', '0005_remove_dailyactivity_pk_dailyactivity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='pk',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
    ]
