# Generated by Django 6.1 on 2026-08-13 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password_hash', models.CharField(blank=True, help_text='Null for OAuth users.', max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('xp', models.PositiveIntegerField(default=0, help_text='Total experience points earned.')),
                ('gems', models.PositiveIntegerField(default=500, help_text='Mocked in-app currency.')),
                ('hearts', models.PositiveSmallIntegerField(default=5, help_text='Current hearts balance.')),
                ('max_hearts', models.PositiveSmallIntegerField(default=5, help_text='Maximum allowed hearts.')),
                ('last_heart_loss_at', models.DateTimeField(blank=True, null=True)),
                ('streak_count', models.PositiveIntegerField(default=0, help_text='Current daily active streak.')),
                ('last_active_date', models.DateField(blank=True, help_text='Last date on which the user completed activity.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.user')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('user_id', 'date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='users.user')),
            ],
            options={
                'db_table': 'user_daily_activity',
                'ordering': ['-date'],
            },
        ),
    ]
