# Generated by Django 5.2.1 on 2026-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the user selected/activated this course.'),
        ),
    ]
