# Generated by Django 6.1 on 2026-08-15 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usercourse_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='pk',
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_activity'),
        ),
    ]
